### ISSUE TITLE
[Bug Report] Crashes on app Split view

### ISSUE THREAD

**Issue by shuvashish76** [SmartPack/PackageManager#34]
**Crash log**

FATAL EXCEPTION: main
Process: com.smartpack.packagemanager, PID: 21103
java.lang.IllegalStateException: Fragment v0{cc7d226 (adc5e4d1-f42d-416b-889c-e0290278ffe1)} not attached to Activity
	at androidx.fragment.app.Fragment.W(:1)
	at b.c.a.c.w.onMenuItemClick(:6)
	at a.b.h.k0.b(Unknown Source:6)
	at a.b.g.i.g.e(Unknown Source:4)
	at a.b.g.i.g.s(:1)
	at a.b.g.i.k.onItemClick(:4)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1181)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3150)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

---
It is basically the same type crash as

https://github.com/TeamAmaze/AmazeFileManager/issues/2752
https://github.com/zhanghai/MaterialFiles/issues/574

**Comment by sunilpaulmathew** [comment]
@shuvashish76 
Thanks for raising this issue. As per the comment from the Material Files developers, I expected to reproduce the same here. Surprisingly, it won't happen on my phone, running Android 11 Lineage OS. What about your device configuration. I also have no idea to deal with it at this moment. So, I'll keep it open.

**Comment by shuvashish76** [comment]
**Device info**
App version: 4.9 (F-droid)
Android release version: 8.1.0
Device model: Lenovo Tab4 8plus (TB-8704X)
