### ISSUE TITLE
App crash while changing input method

### ISSUE THREAD

**Issue by Giga-Pudding** [SmartPack/PackageManager#71]
**Describe the bug**
I was running PackageManager, everything was fine. But i was not familiar with the new gesture control of my new android phone (i was using an ald Samsung Galaxy S7 with Android 8, before). So without closing the PackageManager App, i switched to my phones settings menü and enabled the good old "3 button navigation bar". In that moment, the PackageManager App which was still running, but in the background, crashed.

**Crash logs**
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at x1.d.a(Unknown Source:8)
	at x1.h.c(:11)
	at w1.l$d.a(Unknown Source:6)
	at c2.c.run(:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Device info**
 - Device: Nokia G10
 - OS Version: Android 11
 - App Manager Version: 5.9
 - Mode: no-root

**Comment by sunilpaulmathew** [comment]
@Giga-Pudding 
Thanks for reporting this issue.
Just to clarify, if this issue occur only when you do the mentioned processes. I mean, after the crash, app started and works just normal?

**Comment by Giga-Pudding** [comment]
exactly! This crash only happens in that moment, when doing the android input config change. After that, PackageManager can be started again, and works fine.

**Comment by sunilpaulmathew** [comment]
> exactly! This crash only happens in that moment, when doing the android input config change. After that, PackageManager can be started again, and works fine.

In that case, I'll just leave it, as it won't affect most majority of users.
