### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Wjxfi** [SmartPack/PackageManager#99]
During uninstallation of miui system app during the uninstallation screen, the app stopped. Then I got kicked out of the app

I've managed to destroy either com.miui.bugreport or com.miui.analytics

miui 13.0.5, android 12, v6.9 f-droid

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at p2.i.c(SourceFile:8)
	at o2.o$d.a(Unknown Source:6)
	at androidx.activity.g.run(SourceFile:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by rushduhhp** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at p2.i.c(SourceFile:8)
	at o2.o$d.a(Unknown Source:6)
	at androidx.activity.g.run(SourceFile:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.
